# Copyright 2017-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.0

EAPI=7

CRATES="
cargo-lock-6.0.1
autocfg-1.0.1
fixedbitset-0.2.0
form_urlencoded-1.0.0
gumdrop-0.8.0
gumdrop_derive-0.8.0
hashbrown-0.9.1
idna-0.2.0
indexmap-1.6.1
matches-0.1.8
percent-encoding-2.1.0
pest-2.1.3
petgraph-0.5.1
proc-macro2-1.0.24
quote-1.0.8
semver-0.11.0
semver-parser-0.10.2
serde-1.0.123
serde_derive-1.0.123
syn-1.0.60
tinyvec-1.1.1
tinyvec_macros-0.1.0
toml-0.5.8
ucd-trie-0.1.3
unicode-bidi-0.3.4
unicode-normalization-0.1.16
unicode-xid-0.2.1
url-2.2.0
"

inherit cargo

DESCRIPTION="Self-contained Cargo.lock parser with optional dependency graph analysis"
HOMEPAGE="https://github.com/rustsec/cargo-lock"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="|| ( Apache-2.0 MIT )"
SLOT="0"
KEYWORDS="amd64 arm64"

src_configure() {
	local myfeatures=(
		cli
		dependency-tree
	)
	cargo_src_configure
}
