# Copyright 2017-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.0

EAPI=7

CRATES="
autocfg-1.0.1
block-buffer-0.7.3
block-padding-0.1.5
byte-tools-0.3.1
byteorder-1.3.4
cargo-lock-6.0.0
digest-0.8.1
fake-simd-0.1.2
fixedbitset-0.2.0
generic-array-0.12.3
gumdrop-0.8.0
gumdrop_derive-0.8.0
hashbrown-0.9.1
idna-0.2.0
indexmap-1.6.0
maplit-1.0.2
matches-0.1.8
opaque-debug-0.2.3
percent-encoding-2.1.0
pest-2.1.3
pest_derive-2.1.0
pest_generator-2.1.3
pest_meta-2.1.3
petgraph-0.5.1
proc-macro2-1.0.24
quote-1.0.3
quote-1.0.7
semver-0.11.0
semver-parser-0.10.0
serde-1.0.116
serde_derive-1.0.116
sha-1-0.8.2
syn-1.0.42
tinyvec-0.3.4
toml-0.5.6
typenum-1.12.0
ucd-trie-0.1.3
unicode-bidi-0.3.4
unicode-normalization-0.1.13
unicode-xid-0.2.1
url-2.1.1
"

inherit cargo

DESCRIPTION="Self-contained Cargo.lock parser with optional dependency graph analysis"
HOMEPAGE="https://github.com/rustsec/cargo-lock"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="|| ( Apache-2.0 MIT )"
SLOT="0"
KEYWORDS="~amd64 ~arm64"

src_prepare() {
	rm Cargo.lock || die
	default
}

src_configure() {
	local myfeatures=(
		cli
		dependency-tree
	)
	cargo_src_configure
}
